### ISSUE TITLE
How to add BIO-Bert as a transformer setting in configuration file?

### ISSUE THREAD

**Issue by ShubhamDarak37** [Alibaba-NLP/CLNER#10]
I want to use Bio-Bert as a transformer, so where in the config file should I make changes. I also went through flair/embedding.py but there was no mention of Bio-Bert.

**Comment by wangxinyu0922** [comment]
Hi, I have uploaded the config files.

**Comment by ShubhamDarak37** [comment]
Thank you for the help.
