### ISSUE TITLE
How to config yaml to train the model using BC5CDR, NCBI disease dataset?

### ISSUE THREAD

**Issue by domyown** [Alibaba-NLP/CLNER#11]
> I was succeed to reproduce training the model based on WNUT 17, so I want to try to train the model using BC5CDR, NCBI disease dataset. Could you upload yaml that you used when experimenting on these datasets or which arguments do i need to change(including data folder)?

**Comment by ShubhamDarak37** [comment]
I have the same question, As we are experimenting on Bio-Medical datasets we need to use Bio-Bert as a transformer as mentioned in the paper to reproduce the scores. If Domain-specific configuration files can be uploaded then it will be of great help.

**Comment by domyown** [comment]
Yes.. For me, the purpose of the training is NER. Please give me an advice. Thank you.

**Comment by wangxinyu0922** [comment]
Hi all @goodmary1121 @shubbham37 , I have uploaded the configuration for the bio-medical datasets. By the way, you may refer to `https://huggingface.co/models` to use other transformer-based embeddings.

**Comment by ShubhamDarak37** [comment]
Thank you for the help

**Comment by domyown** [comment]
Thank you!!! :)
