### ISSUE TITLE
Request for explanation regarding testing the model with some text

### ISSUE THREAD

**Issue by domyown** [Alibaba-NLP/CLNER#12]
Thank you for your help that I can train the model on the biomedical datasets with my own datasets. Now I want to try to test the model with some text. There are some files in 'tests' folder, but could you explain more? (Is there main function to implement all your functions for testing the model?.. I am confused.)

**Comment by wangxinyu0922** [comment]
Hi,

If you want to parse the files with your own datasets, please refer to [Parse Files](https://github.com/Alibaba-NLP/CLNER#parse-files). 

I'm not sure which `tests` folder you are referring to. I suspect you mean the files in `CLNER_datasets`. For the folders ends with `bertscore_eos_doc_full`, these names mean the datasets contain the retrieved context. (Therefore, you need to retrieve the contexts for your own datasets.)

**Comment by domyown** [comment]
![image](https://user-images.githubusercontent.com/43026521/140261310-fc374551-0a58-4c43-b58a-af0bde14d531.png)


I made the file in which i want to parse. Is it right(It doesn't matter what the file extension(e.g. csv, xlsx...) is?)?

**Comment by domyown** [comment]
Because after loading my file, 

![image](https://user-images.githubusercontent.com/43026521/140262183-d4643c85-e8d6-48f7-ae66-916dd5f7e48d.png)

the shell didn't continue....training.

**Comment by wangxinyu0922** [comment]
The program stopped in the pdb debugging mode due to the formatting of the datasets. You need to follow the BIO formatting for your own datasets. For example, in your image, the label `ner` should be labeled as `B-ner`. Moreover, the label of retrieved contexts should be `B-X`.

**Comment by wangxinyu0922** [comment]
Note that since you need to parse the file, just use label `O` as the dummy tag for your target sentence (again, use `B-X` as the retrieved text)

**Comment by goodmary1121** [comment]
I guess I didn't explain my work properly. 

1. I want to predict the texts based on the trained model. But i think the texts are also used in training and testing. Is this the original NER process? 

2. If this is the original NER process, do i have to make the text to follow the BIO formatting using the libraries such as flair?
