### ISSUE TITLE
Based on your config file ncbi_doc_cl_kl.yaml,  NCBI dataset is used for fine tuning and ncbi_bertscore_eos_doc_full dataset is used for external context, am I right? and can you please provide the information of file which has context retrieval using bertscore. Thank you.

### ISSUE THREAD

**Issue by ShubhamDarak37** [Alibaba-NLP/CLNER#13]

**Comment by wangxinyu0922** [comment]
Hi, both the NCBI dataset and ncbi_bertscore_eos_doc_full dataset are used for fine-tuning in the `ncbi_doc_cl_kl.yaml`. The ncbi_bertscore_eos_doc_full dataset contains the retrieved contexts processed by the bertscore.

**Comment by ShubhamDarak37** [comment]
Thank you, for considering this issue. Can you please provide the name of the file where you are using Bertscore for external context extraction from ncbi_bertscore_eos_doc_full dataset.

**Comment by wangxinyu0922** [comment]
The external contexts are extracted from google, you can use any google crawler to fetch the external contexts from google. The bertscore is used for reranking. To rerank the retrieved contexts, you can follow the instruction of [bertscore](https://github.com/Tiiiger/bert_score). You can also see [bert_scoring.py](https://github.com/Alibaba-NLP/CLNER/blob/main/tools/bert_scoring.py) for reference, but you need to prepare your own files for the reranking.

**Comment by ShubhamDarak37** [comment]
Okay got it. Thank you for your time.
