### ISSUE TITLE
How to run CLNER on WNUT16

### ISSUE THREAD

**Issue by FishSeeker** [Alibaba-NLP/CLNER#14]
Hi, I'd like to get some results on WNUT16, but I didn't find the *yaml file for wnut16 in config/. May I know how to run CLNER on WNUT16?

**Comment by wangxinyu0922** [comment]
Hi, simply follow the config for wnut17 and modify the `data_folder`

**Comment by Changxi-Liu** [comment]
> Hi, simply follow the config for wnut17 and modify the `data_folder`

Thanks for your reply.
I have changed the config file to be like:
```
 59   ColumnCorpus-WNUTDOCFULL:
 60     column_format:
 61       0: text
 62       1: ner
 63     data_folder:  /path/to/CLNER/CLNER_datasets/wnut16_bertscore_eos_doc_full
 64     tag_to_bioes: ner
 65   Corpus: ColumnCorpus-WNUTDOCFULL
```
But It seems that flair can not tell the tag and produces plenty of < unknown > tag. Can you share us with the right Corpus name? Thanks.

**Comment by wangxinyu0922** [comment]
You also need to specify a new `tag_dictionary` for the wnut16 dataset (as mentioned in [train on your own dataset](https://github.com/Alibaba-NLP/CLNER#train-on-your-own-dataset)), otherwise the code will read the created tag dictionary for WNUT17

**Comment by Changxi-Liu** [comment]
> `tag_dictionary`

Oh. Excellent. I will try your suggestion. Thanks
