### ISSUE TITLE
CoNLL03 configs to reproduce CL-KL performance

### ISSUE THREAD

**Issue by tomaarsen** [Alibaba-NLP/CLNER#17]
Hello!

I was interested in looking at your configuration setup for CoNLL03 in order to reproduce the 93.21 F1 for your [CL-KL paper](https://arxiv.org/pdf/2105.03654.pdf), but I couldn't find it in your [configs](https://github.com/Alibaba-NLP/CLNER/tree/main/config). Have you released the configuration files for CoNLL03?

- Tom Aarsen

**Comment by wangxinyu0922** [comment]
You can change the dataset in one of the config to conll03 to reproduce our result

**Comment by tomaarsen** [comment]
Alright, thank you. I'll close this.
