### ISSUE TITLE
`pip install -r requirements.txt` does not run properly with python 3.7 and 3.8

### ISSUE THREAD

**Issue by ciaochiaociao** [Alibaba-NLP/CLNER#2]
Hello, I have tried to implement your model in my machine and install the required packages by `pip install -r requirements.txt` but it failed on some packages installation.

```
...
ERROR: Could not find a version that satisfies the requirement mkl-fft==1.0.6 (from versions: 1.3.0)
ERROR: No matching distribution found for mkl-fft==1.0.6
```

I have tried with python 3.7 and 3.8 version, and they all failed.

Can you check that for me?

Thank you.

**Comment by wangxinyu0922** [comment]
You can ignore this package by commanding this line out in `requirements.txt`. You may see [this issue](https://github.com/Alibaba-NLP/ACE/issues/5#issuecomment-873810236) for more details.

**Comment by ciaochiaociao** [comment]
> You can ignore this package by commanding this line out in `requirements.txt`. You may see [this issue](https://github.com/Alibaba-NLP/ACE/issues/5#issuecomment-873810236) for more details.

I have also commented out the lines, but it showed other errors on other packages

But it then showed other errors:

```
ERROR: Could not find a version that satisfies the requirement tensorflow==1.13.1 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0, 2.4.1, 2.4.2, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.5.0, 2.6.0rc0, 2.6.0rc1)
ERROR: No matching distribution found for tensorflow==1.13.
```

**Comment by wangxinyu0922** [comment]
You may command this line out as well since tensorflow is not used in this package

**Comment by ciaochiaociao** [comment]
I see. Thank you. I have also tried to replace the requirements.txt file with the one mentioned in [this issue](https://github.com/Alibaba-NLP/ACE/issues/5#issuecomment-873810236) for more details. And it works. But a new issue is found and I reported in a new issue.
