### ISSUE TITLE
Reproduction of the experiment WITHOUT cooperative learning

### ISSUE THREAD

**Issue by ciaochiaociao** [Alibaba-NLP/CLNER#6]
Hello,

I am currently trying to reproduce the results given in your paper. I have just run
`python train.py --config wnut17_doc.yaml` with 5 runs, which gives the micro-f1 scores of
58.68
59.85
60.78
58.71
59.72
and averages at 59.55, which is quite less than the performance of 60.20 reported in your paper. (see the figure below)

![image](https://user-images.githubusercontent.com/13917478/135898348-781c2073-e013-49dc-ba49-5ce2bca77e7a.png)

Is the config file `wnut17_doc.yaml` used for this experiment? Is there something I missed or did wrong?

**Comment by wangxinyu0922** [comment]
Hi, models trained on the WNUT datasets have a larger variance than the others, you may try to run more times.

**Comment by ciaochiaociao** [comment]
--- Update ---
I train another five runs again:
59.25
60.19
58.90
60.17
60.06
These average at 59.71.

All 10 runs will average at 59.63.

However, if I train with **20 epochs** (instead of 10 epochs by default) for 10 runs, this averages at **60.46**.

All above experiments use the default settings, where no warmup is turned on. Did you use any warmup in your paper?

**Comment by wangxinyu0922** [comment]
I did not use warmup in my experiments. I'm not sure for the reason and I suspect the mismatch of the results is possibly due to the environments (for example, the CUDA version and GPU hardware). I think setting of 20 epochs is reasonable as well. You may use this setting in your experiments.
