### ISSUE TITLE
Processing of the Retrieved Results of Google Search Engine

### ISSUE THREAD

**Issue by ciaochiaociao** [Alibaba-NLP/CLNER#8]
Hello,

I would like to ask you how you process the results returned from Google Search Engine. Specifically,
 1. How do you handle `title` and `snippet`? Do you just add title as an independent sentence (where title and snippet will be ranked and selected separately) or prepend/append with the snippet (where the concatenated sentence will be ranked)? 
 2. How do you handle the incompleteness of the snippet (i.e., the snippet with the ellipsis `...`)? 
 3. In your paper, what did you mean by 
     > We filter the retrieved texts that contain any part of the datasets.

**Comment by wangxinyu0922** [comment]
Hi,

1. I take the title and snippet separatedly.
2. I just keep the sentence to the ellipsis `...` as the sentence.
3. The process aims at avoiding the retrieved sentence is identical to one of the sentences in the dataset.
